CREATE TABLE bank_user
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(30)                              NOT NULL,
    name     VARCHAR(250),
    age      INTEGER,
    CONSTRAINT pk_bank_user PRIMARY KEY (id)
);

INSERT INTO bank_user(username, name, age)
VALUES ('pedro', 'Pedro', 12),
       ('maria', 'Maria', 24);
